### PR TITLE
Adds transformations to Mapping. Fixes minor issues found during implementation

### PR DESCRIPTION
**Pull request by dropdevcoding**
* Adds capability to use ValueObjects as property values being (de-)hydrated before/after persisting / loading.

* Fixes minor bug in primary key -> column mapping (wasn't found because property had the same name)

* Fixes minor bug with insert return value: SQLite always returns RowID which leads to misbehavior if not using generatedValue in mapping. Now returning the provided value instead if generatedValue is not provided

### CODE REVIEW

**Comment by dropdevcoding** [comment]
Background: 

Instead of doing a hardfork I want to share / discuss this feature with you in case you probably want to have it in your codebase as well since I love open source and I very appreciate your approach doing things in comparison to imho slightly bloated TypeORM. 

This PR enables to define transformation functions for fields / properties within the mapping as:

```

**Comment by RWOverdijk** [comment]
Couldn't you just use javascript getters and setters for this? It's what I do. I like to use javascript as much as possible for the best performance :)

**Comment by dropdevcoding** [comment]
That would be also possible from a technical perspective and I also agree on the performance aspect but since I want to use wetland in a DDD environment this approach would have severe negative impact on my domain model so unfortunately this is no option for me.

**Comment by RWOverdijk** [comment]
Would it? Because I'm fine with internally calling getters if configured as such. That way you don't have to call those methods yourself and it's automatic. I'd love a feature like this but I think the PR is a bit all-touching. Dirty checks for example require dehydration, as would toJSON etc.

Otherwise, this PR might take a while but I'll do my best. At a first glance it's just about linting and commit messages. I haven't looked into it too deep yet (unfortunately I'm a bit busy). If you could slim it down to the essentials it'd help me a lot!

Regardless, thank you for keeping the spirit of OSS alive and submitting a PR.

**Comment by dropdevcoding** [comment]
I'm sorry for mixing fixes with the feature. While implementing the feature and running the tests I stumbled upon minor issues which I directly fixed, that's why it is a bit cluttered.

The feature touches that many classes because it supports on the one side mapping for persistence / loading as well as the QueryBuilder itself. I tried to centralize it as good as possible but it some cases it isn't the responsibility of the according class to apply it. 

Would it help you to have one PR for the fixes (one fix each commit) and another for the new feature?

**Comment by dropdevcoding** [comment]
I provided the mentioned fixes in another PR #240 
I tried to adhere to conventional commits but obviously didn't get it correctly - sorry for that

**Comment by RWOverdijk** [comment]
It's a missing space. 

`feat(Mapping): Adds capability to use ValuObjects as property values b…`

**Comment by RWOverdijk** [comment]
With the coming release (a PR will land today or tomorrow), a couple of issues you tackled with this PR have been resolved. If you want to submit incremental PRs after that, I'd be grateful.

Otherwise, I'm sure I'll refer to this PR a couple of times as I submit more fixes (some of the fixes in this PR weren't quite correct).

Thanks again for your efforts!

**Pull request closed without merging**
