### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by dropdevcoding**
This PR provides some minor fixes found during feature implementation (one fix per commit)

### CODE REVIEW

**Comment by RWOverdijk** [comment]
The codestyle and commit messages aren't correct yet. If you want, I can just apply these changes for you when I have time.

**Comment by dropdevcoding** [comment]
Since I obviously didn't get it yet, it would be nice if you could so. Afterwards I will have a look at your changes to see what was wrong there.

**Comment by RWOverdijk** [comment]
It's mainly aligning consecutive assignments, semicolons and newlines. I'll give it a go asap (sorry if it takes a while, hectic life of a developer haha)

**Comment by dropdevcoding** [comment]
Alright, thanks for having a look but no need to hurry :-)

**Pull request closed without merging**
