### PR TITLE
Fix/no pk refresh

### LINKED ISSUE #244: insert: TypeError: Cannot convert undefined or null to object
The error occurred in MYSQL(MariaDB) and Sqllite so far. Didn't test other Databases.

If you have a table with no autoincrement, you will get the error everytime you persist data in the table.

The data is successfully written, but you will get the error anyway.

Error: TypeError: Cannot convert undefined or null to object

### PR DESCRIPTION
**Pull request by RWOverdijk**
Fixes #244 and #245 

- Adds an error when trying to refresh an entity without AI.
- Adds options to override for commit and flush

### CODE REVIEW

**Comment by wsjwa** [comment]
Ok i'll try it out as soon as i get to it. First i have to see how to use scope. I don't use it at the moment.

**Comment by RWOverdijk** [comment]
How can you not use scope? Do you work directly with the entity manager? Because you really shouldn't.

If you call getManager() you get a Scope instance. Perhaps you're using it but you just don't know.

**Comment by wsjwa** [comment]
I work with getManager().getRepository('Entity') so far. Is there an init for a scope integrated?

**Comment by RWOverdijk** [comment]
@wsjwa That is a Scope instance :) The result of getManager.

A scope is needed because node servers persist whereas others reinitialize (like PHP or (generally) Java, both having JPA spec based libraries). A scope is the same as an EntityManager but it's temporary and should be bound to the context of a request or operation.

Calling getManager() initializes a new scope, with a new unit of work and new identity map (optimized for performance).

Either way, you should be able to update and call flush() with the options I documented above.

**Comment by wsjwa** [comment]
Good to know :) 

I don't know if i have the time to try the fix today. Too many todos :)

**Comment by RWOverdijk** [comment]
I'll merge this soon. It'll be a major version bump, so you should be safe.

**Comment by edouardmenayde** [comment]
I have not worked on wetland's code for a while and I don't have my laptop so that's kind of hard to review from my phone. I could maybe find some time next week to review it but it seems like it won't fit in your timeline.

**Comment by RWOverdijk** [comment]
@edouardmenayde There's no real timeline. I can wait another week if @wsjwa can :)

**Comment by edouardmenayde** [comment]
@RWOverdijk It looks good to me !

**Comment by wsjwa** [comment]
@RWOverdijk i can wait :)

**Comment by RWOverdijk** [comment]
@wsjwa I'd really rather have you test before I release this. 

@edouardmenayde can you mark it as accepted?

**Comment by wsjwa** [comment]
I just updated to the latest version and tried a create with the new flush options.
The error regarding the return value is fixed, but now u won't get the correct id(primary-key value) in entities afterCreate().
id = count of records in table. Every other field value is correct.

**Comment by wsjwa** [comment]
Additionally what flush config do i need to get a auto_increment generated id?

**Comment by RWOverdijk** [comment]
@wsjwa That should just work when set. I think the issue is that it doesn't identify the foreign key and just sets the return value, expecting it to be the PK while in fact it's the number of changed records.

**Comment by wsjwa** [comment]
And updates don't return the number of affected rows.
Expected behavior?

**Comment by RWOverdijk** [comment]
Yes, in this case. But you can find the number of updates that will be performed by asking the unit of work.

If you think you should be getting the number of affected rows, I think I can agree. It should be easy enough to implement, but that should probably be a different issue.

It's really easier to talk about if you [join us on slack](https://spoonx-slack.herokuapp.com/).

**Pull request merged**
