### PR TITLE
fix(snapshot-manager): Nulleable option in joinColumn fields

### PR DESCRIPTION
**Pull request by elxris**
This is a expected behaviour as the documentation says so.

Solves #215

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@elxris Thanks a lot! Almost perfect. If you could rename your commit to:

`fix(SnapshotManager): use nullable value for joinColumn from mapping`

Then I'll publish this fix asap.

**Comment by elxris** [comment]
Done. Thank you.

**Comment by RWOverdijk** [comment]
@edouardmenayde Could you add your review?

**Comment by edouardmenayde** [comment]
:+1: That's a pretty safe fix :-)
Very happy to welcome a new contributor !

**Comment by RWOverdijk** [comment]
Published as 2.3.2

Thanks again!

**Pull request merged**
